In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import statsmodels.api as sm
from scipy.stats import boxcox

pd.options.display.max_rows = 50

# Activites List

### Activity 1

- Aggregate data into one Data Frame using Pandas.
- Standardizing header names
- Deleting and rearranging columns – delete the column customer as it is only a unique identifier for each row of data
- Working with data types – Check the data types of all the columns and fix the incorrect ones (for ex. customer lifetime value and number of complaints )
- Filtering data and Correcting typos – Filter the data in state and gender column to standardize the texts in those columns
- Removing duplicates
- Replacing null values – Replace missing values with means of the column (for numerical columns)

In [2]:
file1 = pd.read_csv('data/file1.csv')

In [3]:
file1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Customer                   1071 non-null   object 
 1   ST                         1071 non-null   object 
 2   GENDER                     954 non-null    object 
 3   Education                  1071 non-null   object 
 4   Customer Lifetime Value    1068 non-null   object 
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   object 
 8   Policy Type                1071 non-null   object 
 9   Vehicle Class              1071 non-null   object 
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB


In [4]:
file2 = pd.read_csv('data/file2.csv')

In [5]:
file2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 996 entries, 0 to 995
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Customer                   996 non-null    object 
 1   ST                         996 non-null    object 
 2   GENDER                     991 non-null    object 
 3   Education                  996 non-null    object 
 4   Customer Lifetime Value    992 non-null    object 
 5   Income                     996 non-null    int64  
 6   Monthly Premium Auto       996 non-null    int64  
 7   Number of Open Complaints  996 non-null    object 
 8   Total Claim Amount         996 non-null    float64
 9   Policy Type                996 non-null    object 
 10  Vehicle Class              996 non-null    object 
dtypes: float64(1), int64(2), object(8)
memory usage: 85.7+ KB


In [6]:
file3 = pd.read_csv('data/file3.csv')

In [7]:
file3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7070 entries, 0 to 7069
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Customer                   7070 non-null   object 
 1   State                      7070 non-null   object 
 2   Customer Lifetime Value    7070 non-null   float64
 3   Education                  7070 non-null   object 
 4   Gender                     7070 non-null   object 
 5   Income                     7070 non-null   int64  
 6   Monthly Premium Auto       7070 non-null   int64  
 7   Number of Open Complaints  7070 non-null   int64  
 8   Policy Type                7070 non-null   object 
 9   Total Claim Amount         7070 non-null   float64
 10  Vehicle Class              7070 non-null   object 
dtypes: float64(2), int64(3), object(6)
memory usage: 607.7+ KB


In [8]:
# call the function for file3
def rename_columns(file3):
    file3.rename(columns={'State': 'ST', 'Gender': 'GENDER'}, inplace=True )
    return file3

In [9]:
rename_file3 = rename_columns(file3)

In [10]:
file1.info()
file2.info()
rename_file3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Customer                   1071 non-null   object 
 1   ST                         1071 non-null   object 
 2   GENDER                     954 non-null    object 
 3   Education                  1071 non-null   object 
 4   Customer Lifetime Value    1068 non-null   object 
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   object 
 8   Policy Type                1071 non-null   object 
 9   Vehicle Class              1071 non-null   object 
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 996 entries, 0 to 995
Data columns (total 11 columns):
 #   C

In [11]:
def aggregate ():
    file1 = pd.read_csv('data/file1.csv')
    file2 = pd.read_csv('data/file2.csv')
    rename_file3
    return pd.concat([file1, file2, rename_file3], axis=0)


In [12]:
ca_df = aggregate ()

In [13]:
list(ca_df.columns)

['Customer',
 'ST',
 'GENDER',
 'Education',
 'Customer Lifetime Value',
 'Income',
 'Monthly Premium Auto',
 'Number of Open Complaints',
 'Policy Type',
 'Vehicle Class',
 'Total Claim Amount']

In [14]:
def lower_case_column_names(ca_df):
    ca_df.columns=[i.lower() for i in ca_df.columns]
    return ca_df

In [15]:
lower_case_column_names(ca_df)

customer          st gender             education  \
0     RB50392  Washington    NaN                Master   
1     QZ44356     Arizona      F              Bachelor   
2     AI49188      Nevada      F              Bachelor   
3     WW63253  California      M              Bachelor   
4     GA49547  Washington      M  High School or Below   
...       ...         ...    ...                   ...   
7065  LA72316  California      M              Bachelor   
7066  PK87824  California      F               College   
7067  TD14365  California      M              Bachelor   
7068  UP19263  California      M               College   
7069  Y167826  California      M               College   

     customer lifetime value   income  monthly premium auto  \
0                        NaN      0.0                1000.0   
1                 697953.59%      0.0                  94.0   
2                1288743.17%  48767.0                 108.0   
3                 764586.18%      0.0                 106.0   
4                 536307.65%  36357.0                  68.0   
...                      ...      ...                   ...   
7065             23405.98798  71941.0                  73.0   
7066             3096.511217  21604.0                  79.0   
7067             8163.890428      0.0                  85.0   
7068             7524.442436  21941.0                  96.0   
7069             2611.836866      0.0                  77.0   

     number of open complaints     policy type  vehicle class  \
0                       1/0/00   Personal Auto  Four-Door Car   
1                       1/0/00   Personal Auto  Four-Door Car   
2                       1/0/00   Personal Auto   Two-Door Car   
3                       1/0/00  Corporate Auto            SUV   
4                       1/0/00   Personal Auto  Four-Door Car   
...                        ...             ...            ...   
7065                         0   Personal Auto  Four-Door Car   
7066                         0  Corporate Auto  Four-Door Car   
7067                         3  Corporate Auto  Four-Door Car   
7068                         0   Personal Auto  Four-Door Car   
7069                         0  Corporate Auto   Two-Door Car   

      total claim amount  
0               2.704934  
1            1131.464935  
2             566.472247  
3             529.881344  
4              17.269323  
...                  ...  
7065          198.234764  
7066          379.200000  
7067          790.784983  
7068          691.200000  
7069          369.600000  

[12074 rows x 11 columns]

In [16]:
# delete the column customer as it is only a unique identifier for each row of data
def drop_columns(ca_df) :
    ca_df.drop(columns=['customer'], inplace=True)
    return ca_df

In [17]:
ca_df = drop_columns(ca_df)

In [18]:
ca_df

st gender             education customer lifetime value  \
0     Washington    NaN                Master                     NaN   
1        Arizona      F              Bachelor              697953.59%   
2         Nevada      F              Bachelor             1288743.17%   
3     California      M              Bachelor              764586.18%   
4     Washington      M  High School or Below              536307.65%   
...          ...    ...                   ...                     ...   
7065  California      M              Bachelor             23405.98798   
7066  California      F               College             3096.511217   
7067  California      M              Bachelor             8163.890428   
7068  California      M               College             7524.442436   
7069  California      M               College             2611.836866   

       income  monthly premium auto number of open complaints     policy type  \
0         0.0                1000.0                    1/0/00   Personal Auto   
1         0.0                  94.0                    1/0/00   Personal Auto   
2     48767.0                 108.0                    1/0/00   Personal Auto   
3         0.0                 106.0                    1/0/00  Corporate Auto   
4     36357.0                  68.0                    1/0/00   Personal Auto   
...       ...                   ...                       ...             ...   
7065  71941.0                  73.0                         0   Personal Auto   
7066  21604.0                  79.0                         0  Corporate Auto   
7067      0.0                  85.0                         3  Corporate Auto   
7068  21941.0                  96.0                         0   Personal Auto   
7069      0.0                  77.0                         0  Corporate Auto   

      vehicle class  total claim amount  
0     Four-Door Car            2.704934  
1     Four-Door Car         1131.464935  
2      Two-Door Car          566.472247  
3               SUV          529.881344  
4     Four-Door Car           17.269323  
...             ...                 ...  
7065  Four-Door Car          198.234764  
7066  Four-Door Car          379.200000  
7067  Four-Door Car          790.784983  
7068  Four-Door Car          691.200000  
7069   Two-Door Car          369.600000  

[12074 rows x 10 columns]

In [19]:
# get rid of weird data in ca_df['number of open complaints']

In [20]:
ca_df['number of open complaints'].unique()

array(['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan, 0,
       2, 3, 1, 5, 4], dtype=object)

In [21]:
ca_df["number of open complaints"] = list(map(lambda x:int(x[2]) if isinstance(x, str) else x, ca_df["number of open complaints"]))

In [22]:
ca_df['number of open complaints'].unique()

array([ 0.,  2.,  1.,  3.,  5.,  4., nan])

In [23]:
# get rid of % in ca_df['customer lifetime value']

In [24]:
ca_df.dtypes

st                            object
gender                        object
education                     object
customer lifetime value       object
income                       float64
monthly premium auto         float64
number of open complaints    float64
policy type                   object
vehicle class                 object
total claim amount           float64
dtype: object

In [25]:
ca_df['customer lifetime value'].astype(str)

0               nan
1        697953.59%
2       1288743.17%
3        764586.18%
4        536307.65%
           ...     
7065    23405.98798
7066    3096.511217
7067    8163.890428
7068    7524.442436
7069    2611.836866
Name: customer lifetime value, Length: 12074, dtype: object

In [26]:
ca_df['customer lifetime value'] = ca_df['customer lifetime value'].astype(str).str.replace('%', '')

In [27]:
ca_df['customer lifetime value'].unique()

array(['nan', '697953.59', '1288743.17', ..., '8163.890428',
       '7524.442436', '2611.836866'], dtype=object)

In [28]:
#Check the data types of all the columns and 
#fix the incorrect ones (for ex. customer lifetime value and number of complaints)
ca_df.dtypes

st                            object
gender                        object
education                     object
customer lifetime value       object
income                       float64
monthly premium auto         float64
number of open complaints    float64
policy type                   object
vehicle class                 object
total claim amount           float64
dtype: object

In [29]:
ca_df['customer lifetime value'] =  pd.to_numeric(ca_df['customer lifetime value'], errors='coerce')
ca_df['number of open complaints'] =  pd.to_numeric(ca_df['number of open complaints'], errors='coerce')

In [30]:
ca_df.dtypes

st                            object
gender                        object
education                     object
customer lifetime value      float64
income                       float64
monthly premium auto         float64
number of open complaints    float64
policy type                   object
vehicle class                 object
total claim amount           float64
dtype: object

In [31]:
#Filter the data in state and gender column to standardize the texts in those columns
ca_df['gender'].unique()

array([nan, 'F', 'M', 'Femal', 'Male', 'female'], dtype=object)

In [32]:
ca_df['st'].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'Cali',
       'AZ', 'WA', nan], dtype=object)

In [33]:
# list(map(lambda x: "F" if ("[fF]" in x) else x, ca_df['gender'])) 
#no working with  float.. why? gender is an object
ca_df['gender'] = ca_df['gender'].astype(str)

In [34]:
ca_df['gender'] = list(map(lambda x: "F" if ("emal" in x) else x, ca_df['gender']))

In [35]:
ca_df['gender'] = list(map(lambda x: "M" if ("Male" in x) else x, ca_df['gender']))

In [36]:
ca_df['gender'] = list(map(lambda x: "other" if ("nan" in x) else x, ca_df['gender']))

In [37]:
ca_df['gender'].unique()

array(['other', 'F', 'M'], dtype=object)

In [38]:
# Removing duplicates
ca_df.drop_duplicates()

st gender             education  customer lifetime value  \
0     Washington  other                Master                      NaN   
1        Arizona      F              Bachelor             6.979536e+05   
2         Nevada      F              Bachelor             1.288743e+06   
3     California      M              Bachelor             7.645862e+05   
4     Washington      M  High School or Below             5.363077e+05   
...          ...    ...                   ...                      ...   
7065  California      M              Bachelor             2.340599e+04   
7066  California      F               College             3.096511e+03   
7067  California      M              Bachelor             8.163890e+03   
7068  California      M               College             7.524442e+03   
7069  California      M               College             2.611837e+03   

       income  monthly premium auto  number of open complaints  \
0         0.0                1000.0                        0.0   
1         0.0                  94.0                        0.0   
2     48767.0                 108.0                        0.0   
3         0.0                 106.0                        0.0   
4     36357.0                  68.0                        0.0   
...       ...                   ...                        ...   
7065  71941.0                  73.0                        0.0   
7066  21604.0                  79.0                        0.0   
7067      0.0                  85.0                        3.0   
7068  21941.0                  96.0                        0.0   
7069      0.0                  77.0                        0.0   

         policy type  vehicle class  total claim amount  
0      Personal Auto  Four-Door Car            2.704934  
1      Personal Auto  Four-Door Car         1131.464935  
2      Personal Auto   Two-Door Car          566.472247  
3     Corporate Auto            SUV          529.881344  
4      Personal Auto  Four-Door Car           17.269323  
...              ...            ...                 ...  
7065   Personal Auto  Four-Door Car          198.234764  
7066  Corporate Auto  Four-Door Car          379.200000  
7067  Corporate Auto  Four-Door Car          790.784983  
7068   Personal Auto  Four-Door Car          691.200000  
7069  Corporate Auto   Two-Door Car          369.600000  

[8880 rows x 10 columns]

In [39]:
# Replacing null values – Replace missing values with means of the column (for numerical columns)
ca_df[ca_df['customer lifetime value'].isna()==True]
# many nan values!

st gender             education  customer lifetime value  \
0     Washington  other                Master                      NaN   
78    Washington      F                Master                      NaN   
988   Washington      M  High School or Below                      NaN   
1071         NaN  other                   NaN                      NaN   
1072         NaN  other                   NaN                      NaN   
...          ...    ...                   ...                      ...   
4007         NaN  other                   NaN                      NaN   
325   Washington      M  High School or Below                      NaN   
372   Washington  other  High School or Below                      NaN   
580   Washington      M                Master                      NaN   
861   Washington      F             Bachelors                      NaN   

       income  monthly premium auto  number of open complaints    policy type  \
0         0.0                1000.0                        0.0  Personal Auto   
78    41275.0                  96.0                        0.0  Personal Auto   
988   55561.0                  63.0                        0.0  Personal Auto   
1071      NaN                   NaN                        NaN            NaN   
1072      NaN                   NaN                        NaN            NaN   
...       ...                   ...                        ...            ...   
4007      NaN                   NaN                        NaN            NaN   
325   51878.0                  66.0                        1.0  Personal Auto   
372   36765.0                  66.0                        1.0  Personal Auto   
580       0.0                  70.0                        0.0  Personal Auto   
861   25859.0                  74.0                        0.0   Special Auto   

      vehicle class  total claim amount  
0     Four-Door Car            2.704934  
78    Four-Door Car           41.122303  
988   Four-Door Car          227.872071  
1071            NaN                 NaN  
1072            NaN                 NaN  
...             ...                 ...  
4007            NaN                 NaN  
325   Four-Door Car          316.800000  
372   Four-Door Car          320.849072  
580   Four-Door Car          336.000000  
861   Four-Door Car          355.200000  

[2944 rows x 10 columns]

In [40]:
# mean_customer_lifetime_value
mean_customer_lifetime_value = round(np.mean(ca_df['customer lifetime value']), 2)

In [41]:
ca_df['customer lifetime value'] = ca_df['customer lifetime value'].fillna(mean_customer_lifetime_value)

In [42]:
ca_df['customer lifetime value'].unique()

array([ 182196.39    ,  697953.59    , 1288743.17    , ...,
          8163.890428,    7524.442436,    2611.836866])

In [43]:
# mean_income
mean_income = round(np.mean(ca_df['income']), 2)

In [44]:
ca_df['income'] = ca_df['income'].fillna(mean_income)

In [45]:
ca_df['income'].unique()

array([    0., 48767., 36357., ..., 66367., 71941., 21941.])

In [46]:
# mean_monthly_premium_auto
mean_monthly_premium_auto = round(np.mean(ca_df['monthly premium auto']), 2)

In [47]:
ca_df['monthly premium auto'] = ca_df['monthly premium auto'].fillna(mean_monthly_premium_auto)

In [48]:
ca_df['monthly premium auto'].unique()

array([ 1000.  ,    94.  ,   108.  ,   106.  ,    68.  ,    69.  ,
          67.  ,   101.  ,    71.  ,    93.  ,   110.  ,    70.  ,
          64.  ,    72.  ,    74.  ,    79.  ,    73.  ,    61.  ,
         111.  ,    80.  ,    63.  ,   237.  ,    65.  ,   130.  ,
          62.  ,   117.  ,    91.  ,    90.  ,    66.  ,    99.  ,
         103.  , 35354.  ,   172.  ,    92.  ,   104.  ,   113.  ,
         124.  ,   105.  ,   100.  ,   112.  ,    97.  ,    95.  ,
         102.  ,    96.  ,   186.  ,    77.  ,    76.  ,   119.  ,
          87.  ,   109.  ,   107.  ,    88.  ,    85.  ,  6464.  ,
         133.  ,    86.  ,    78.  ,    89.  ,   192.  ,   118.  ,
         140.  ,   127.  ,   126.  ,    82.  ,   115.  ,   217.  ,
         114.  ,   138.  ,    81.  ,   255.  ,   150.  ,   123.  ,
         116.  ,   190.  ,    98.  ,   159.  ,    84.  ,    83.  ,
         152.  ,   136.  ,   245.  ,   135.  ,  1005.  ,   225.  ,
         132.  ,   153.  ,   121.  ,   139.  ,   154.  ,   161

In [49]:
#mean_number_of_open_complaints
mean_number_of_open_complaints = round(np.mean(ca_df['number of open complaints']), 2)

In [50]:
ca_df['number of open complaints'] = ca_df['number of open complaints'].fillna(mean_number_of_open_complaints)

In [51]:
ca_df['number of open complaints'].unique()

array([0.  , 2.  , 1.  , 3.  , 5.  , 4.  , 0.38])

In [52]:
# mean_total_claim_amount
mean_total_claim_amount = round(np.mean(ca_df['total claim amount']))

In [53]:
ca_df['total claim amount'] = ca_df['total claim amount'].fillna(mean_total_claim_amount)

In [54]:
ca_df['total claim amount'].unique()

array([   2.704934, 1131.464935,  566.472247, ...,  541.282007,
        198.234764,  790.784983])

### Activity 2

- Bucketing the data - Write a function to replace column "State" to different zones. California as West Region, Oregon as North West, and Washington as East, and Arizona and Nevada as Central
- Standardizing the data – Use string functions to standardize the text data (lower case)

In [55]:
ca_df['st'] = ca_df['st'].astype("str")

In [56]:
ca_df['st']
#there are double keys that need to be cleaned

0       Washington
1          Arizona
2           Nevada
3       California
4       Washington
           ...    
7065    California
7066    California
7067    California
7068    California
7069    California
Name: st, Length: 12074, dtype: object

In [57]:
ca_df['st'] = list(map(lambda x: "Arizona" if ("AZ" in x) else x, ca_df['st']))
ca_df['st'].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'Cali',
       'WA', 'nan'], dtype=object)

In [58]:
ca_df['st'] = list(map(lambda x: "California" if ("Cali" in x) else x, ca_df['st']))
ca_df['st'].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'WA',
       'nan'], dtype=object)

In [59]:
ca_df['st'] = list(map(lambda x: "Washington" if ("WA" in x) else x, ca_df['st']))
ca_df['st'].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'nan'],
      dtype=object)

In [60]:
ca_df['st'] = ca_df['st'].astype("category")

In [61]:
state_region_labels = {'California': 'West', 'Oregon': 'North West', 'Washington': 'East', 'Nevada': 'Central', 'Arizona': 'Central'}

In [62]:
ca_df['st'].replace(state_region_labels, inplace = True)

In [63]:
ca_df['st']

0          East
1       Central
2       Central
3          West
4          East
         ...   
7065       West
7066       West
7067       West
7068       West
7069       West
Name: st, Length: 12074, dtype: object

In [64]:
#Standardizing the data – Use string functions to standardize the text data (lower case)

In [65]:
ca_df.dtypes

st                            object
gender                        object
education                     object
customer lifetime value      float64
income                       float64
monthly premium auto         float64
number of open complaints    float64
policy type                   object
vehicle class                 object
total claim amount           float64
dtype: object

In [66]:
ca_df['st'] = ca_df['st'].str.lower()
ca_df['st']

0          east
1       central
2       central
3          west
4          east
         ...   
7065       west
7066       west
7067       west
7068       west
7069       west
Name: st, Length: 12074, dtype: object

In [67]:
ca_df['gender'] = ca_df['gender'].str.lower()
ca_df['gender']

0       other
1           f
2           f
3           m
4           m
        ...  
7065        m
7066        f
7067        m
7068        m
7069        m
Name: gender, Length: 12074, dtype: object

In [68]:
ca_df['education'] = ca_df['education'].str.lower()
ca_df['education']

0                     master
1                   bachelor
2                   bachelor
3                   bachelor
4       high school or below
                ...         
7065                bachelor
7066                 college
7067                bachelor
7068                 college
7069                 college
Name: education, Length: 12074, dtype: object

In [69]:
ca_df['policy type'] = ca_df['policy type'].str.lower()
ca_df['policy type']

0        personal auto
1        personal auto
2        personal auto
3       corporate auto
4        personal auto
             ...      
7065     personal auto
7066    corporate auto
7067    corporate auto
7068     personal auto
7069    corporate auto
Name: policy type, Length: 12074, dtype: object

In [70]:
ca_df['vehicle class'] = ca_df['vehicle class'].str.lower()
ca_df['vehicle class']

0       four-door car
1       four-door car
2        two-door car
3                 suv
4       four-door car
            ...      
7065    four-door car
7066    four-door car
7067    four-door car
7068    four-door car
7069     two-door car
Name: vehicle class, Length: 12074, dtype: object

In [71]:
ca_df_category = ca_df.select_dtypes(include= 'object', exclude= 'float64')

In [72]:
ca_df.dtypes

st                            object
gender                        object
education                     object
customer lifetime value      float64
income                       float64
monthly premium auto         float64
number of open complaints    float64
policy type                   object
vehicle class                 object
total claim amount           float64
dtype: object

In [73]:
type(ca_df_category)

pandas.core.frame.DataFrame

In [74]:
ca_df_category.isna().sum()

st                  0
gender              0
education        2937
policy type      2937
vehicle class    2937
dtype: int64

In [75]:
ca_df.head()

st gender             education  customer lifetime value   income  \
0     east  other                master                182196.39      0.0   
1  central      f              bachelor                697953.59      0.0   
2  central      f              bachelor               1288743.17  48767.0   
3     west      m              bachelor                764586.18      0.0   
4     east      m  high school or below                536307.65  36357.0   

   monthly premium auto  number of open complaints     policy type  \
0                1000.0                        0.0   personal auto   
1                  94.0                        0.0   personal auto   
2                 108.0                        0.0   personal auto   
3                 106.0                        0.0  corporate auto   
4                  68.0                        0.0   personal auto   

   vehicle class  total claim amount  
0  four-door car            2.704934  
1  four-door car         1131.464935  
2   two-door car          566.472247  
3            suv          529.881344  
4  four-door car           17.269323

### Activity 3

- Which columns are numerical?
- Which columns are categorical?
- Datetime format - Extract the months from the dataset and store in a separate column. Then filter the data to show only the information for the first quarter , ie. January, February and March. Hint: If data from March does not exist, consider only January and February.

In [77]:
#pd.to_datetime(ca_df["effective to date"],format="%m/%d/%y")
#ca_df['month'] = pd.DatetimeIndex(ca_df['effective to date']).month
#print(ca_df['month'])
#ca_df.month.value_counts()